-- Last updated: 8/13/2026, 3:44:38 PM
# Write your MySQL query statement below
SELECT QUERY_NAME, ROUND(AVG(RATING/POSITION), 2) AS QUALITY, 
ROUND(AVG(IF(RATING<3,1,0))*100, 2) AS POOR_QUERY_PERCENTAGE
FROM QUERIES
GROUP BY QUERY_NAME